import { createContext, useContext, useState } from "react";

export interface LanguageOption {
  code: string;
  label: string; // native name
  englishLabel: string;
  shortLabel: string;
  blocked?: boolean; // Pakistan restriction
}

// 100+ languages. Urdu (Pakistan) and Pashto are blocked.
export const LANGUAGE_OPTIONS: LanguageOption[] = [
  // ── English
  { code: "en", label: "English", englishLabel: "English", shortLabel: "EN" },

  // ── Indian Regional Languages
  { code: "hi", label: "हिन्दी", englishLabel: "Hindi", shortLabel: "HI" },
  { code: "gu", label: "ગુજરાતી", englishLabel: "Gujarati", shortLabel: "GU" },
  { code: "ta", label: "தமிழ்", englishLabel: "Tamil", shortLabel: "TA" },
  { code: "te", label: "తెలుగు", englishLabel: "Telugu", shortLabel: "TE" },
  { code: "mr", label: "मराठी", englishLabel: "Marathi", shortLabel: "MR" },
  { code: "bn", label: "বাংলা", englishLabel: "Bengali", shortLabel: "BN" },
  { code: "kn", label: "ಕನ್ನಡ", englishLabel: "Kannada", shortLabel: "KN" },
  { code: "ml", label: "മലയാളം", englishLabel: "Malayalam", shortLabel: "ML" },
  { code: "pa", label: "ਪੰਜਾਬੀ", englishLabel: "Punjabi", shortLabel: "PA" },
  { code: "or", label: "ଓଡ଼ିଆ", englishLabel: "Odia", shortLabel: "OR" },
  { code: "as", label: "অসমীয়া", englishLabel: "Assamese", shortLabel: "AS" },
  { code: "mai", label: "मैथिली", englishLabel: "Maithili", shortLabel: "MAI" },
  { code: "sat", label: "ᱥᱟᱱᱛᱟᱲᱤ", englishLabel: "Santali", shortLabel: "SAT" },
  { code: "ks", label: "كٲشُر", englishLabel: "Kashmiri", shortLabel: "KS" },
  { code: "ne", label: "नेपाली", englishLabel: "Nepali", shortLabel: "NE" },
  { code: "kok", label: "कोंकणी", englishLabel: "Konkani", shortLabel: "KOK" },
  { code: "sd", label: "سنڌي", englishLabel: "Sindhi", shortLabel: "SD" },
  { code: "doi", label: "डोगरी", englishLabel: "Dogri", shortLabel: "DOI" },
  { code: "mni", label: "ꯃꯤꯇꯩꯂꯣꯟ", englishLabel: "Meitei", shortLabel: "MNI" },
  { code: "bho", label: "भोजपुरी", englishLabel: "Bhojpuri", shortLabel: "BHO" },
  {
    code: "raj",
    label: "राजस्थानी",
    englishLabel: "Rajasthani",
    shortLabel: "RAJ",
  },
  {
    code: "hne",
    label: "छत्तीसगढ़ी",
    englishLabel: "Chhattisgarhi",
    shortLabel: "HNE",
  },

  // ── International - European
  { code: "es", label: "Español", englishLabel: "Spanish", shortLabel: "ES" },
  { code: "fr", label: "Français", englishLabel: "French", shortLabel: "FR" },
  { code: "de", label: "Deutsch", englishLabel: "German", shortLabel: "DE" },
  {
    code: "pt",
    label: "Português",
    englishLabel: "Portuguese",
    shortLabel: "PT",
  },
  { code: "it", label: "Italiano", englishLabel: "Italian", shortLabel: "IT" },
  { code: "ru", label: "Русский", englishLabel: "Russian", shortLabel: "RU" },
  { code: "nl", label: "Nederlands", englishLabel: "Dutch", shortLabel: "NL" },
  { code: "pl", label: "Polski", englishLabel: "Polish", shortLabel: "PL" },
  {
    code: "uk",
    label: "Українська",
    englishLabel: "Ukrainian",
    shortLabel: "UK",
  },
  { code: "ro", label: "Română", englishLabel: "Romanian", shortLabel: "RO" },
  { code: "cs", label: "Čeština", englishLabel: "Czech", shortLabel: "CS" },
  { code: "hu", label: "Magyar", englishLabel: "Hungarian", shortLabel: "HU" },
  { code: "sv", label: "Svenska", englishLabel: "Swedish", shortLabel: "SV" },
  { code: "da", label: "Dansk", englishLabel: "Danish", shortLabel: "DA" },
  { code: "fi", label: "Suomi", englishLabel: "Finnish", shortLabel: "FI" },
  { code: "no", label: "Norsk", englishLabel: "Norwegian", shortLabel: "NO" },
  { code: "sk", label: "Slovenčina", englishLabel: "Slovak", shortLabel: "SK" },
  {
    code: "bg",
    label: "Български",
    englishLabel: "Bulgarian",
    shortLabel: "BG",
  },
  { code: "hr", label: "Hrvatski", englishLabel: "Croatian", shortLabel: "HR" },
  { code: "sr", label: "Српски", englishLabel: "Serbian", shortLabel: "SR" },
  { code: "ca", label: "Català", englishLabel: "Catalan", shortLabel: "CA" },
  {
    code: "lt",
    label: "Lietuvių",
    englishLabel: "Lithuanian",
    shortLabel: "LT",
  },
  { code: "lv", label: "Latviešu", englishLabel: "Latvian", shortLabel: "LV" },
  { code: "et", label: "Eesti", englishLabel: "Estonian", shortLabel: "ET" },
  {
    code: "sl",
    label: "Slovenščina",
    englishLabel: "Slovenian",
    shortLabel: "SL",
  },
  { code: "el", label: "Ελληνικά", englishLabel: "Greek", shortLabel: "EL" },
  { code: "tr", label: "Türkçe", englishLabel: "Turkish", shortLabel: "TR" },
  { code: "ka", label: "ქართული", englishLabel: "Georgian", shortLabel: "KA" },
  { code: "hy", label: "Հայերեն", englishLabel: "Armenian", shortLabel: "HY" },
  {
    code: "az",
    label: "Azərbaycan",
    englishLabel: "Azerbaijani",
    shortLabel: "AZ",
  },
  { code: "eu", label: "Euskara", englishLabel: "Basque", shortLabel: "EU" },
  { code: "gl", label: "Galego", englishLabel: "Galician", shortLabel: "GL" },
  {
    code: "is",
    label: "Íslenska",
    englishLabel: "Icelandic",
    shortLabel: "IS",
  },
  {
    code: "lb",
    label: "Lëtzebuergesch",
    englishLabel: "Luxembourgish",
    shortLabel: "LB",
  },
  {
    code: "mk",
    label: "Македонски",
    englishLabel: "Macedonian",
    shortLabel: "MK",
  },
  { code: "sq", label: "Shqip", englishLabel: "Albanian", shortLabel: "SQ" },
  { code: "mt", label: "Malti", englishLabel: "Maltese", shortLabel: "MT" },
  { code: "cy", label: "Cymraeg", englishLabel: "Welsh", shortLabel: "CY" },
  { code: "ga", label: "Gaeilge", englishLabel: "Irish", shortLabel: "GA" },

  // ── International - Asian
  { code: "ja", label: "日本語", englishLabel: "Japanese", shortLabel: "JA" },
  {
    code: "zh",
    label: "中文 (简体)",
    englishLabel: "Chinese Simplified",
    shortLabel: "ZH",
  },
  {
    code: "zh-TW",
    label: "中文 (繁體)",
    englishLabel: "Chinese Traditional",
    shortLabel: "ZHT",
  },
  { code: "ko", label: "한국어", englishLabel: "Korean", shortLabel: "KO" },
  {
    code: "vi",
    label: "Tiếng Việt",
    englishLabel: "Vietnamese",
    shortLabel: "VI",
  },
  { code: "th", label: "ภาษาไทย", englishLabel: "Thai", shortLabel: "TH" },
  {
    code: "id",
    label: "Bahasa Indonesia",
    englishLabel: "Indonesian",
    shortLabel: "ID",
  },
  {
    code: "ms",
    label: "Bahasa Melayu",
    englishLabel: "Malay",
    shortLabel: "MS",
  },
  { code: "tl", label: "Filipino", englishLabel: "Filipino", shortLabel: "TL" },
  { code: "km", label: "ខ្មែរ", englishLabel: "Khmer", shortLabel: "KM" },
  { code: "lo", label: "ລາວ", englishLabel: "Lao", shortLabel: "LO" },
  { code: "my", label: "မြန်မာဘာသာ", englishLabel: "Burmese", shortLabel: "MY" },
  { code: "mn", label: "Монгол", englishLabel: "Mongolian", shortLabel: "MN" },
  { code: "si", label: "සිංහල", englishLabel: "Sinhala", shortLabel: "SI" },
  { code: "uz", label: "O'zbek", englishLabel: "Uzbek", shortLabel: "UZ" },
  { code: "kk", label: "Қазақ", englishLabel: "Kazakh", shortLabel: "KK" },
  { code: "ky", label: "Кыргызча", englishLabel: "Kyrgyz", shortLabel: "KY" },
  { code: "tg", label: "Тоҷикӣ", englishLabel: "Tajik", shortLabel: "TG" },
  { code: "tk", label: "Türkmen", englishLabel: "Turkmen", shortLabel: "TK" },

  // ── International - Middle East & Africa
  { code: "ar", label: "العربية", englishLabel: "Arabic", shortLabel: "AR" },
  { code: "he", label: "עברית", englishLabel: "Hebrew", shortLabel: "HE" },
  {
    code: "fa",
    label: "فارسی",
    englishLabel: "Persian (Farsi)",
    shortLabel: "FA",
  },
  { code: "sw", label: "Kiswahili", englishLabel: "Swahili", shortLabel: "SW" },
  { code: "am", label: "አማርኛ", englishLabel: "Amharic", shortLabel: "AM" },
  { code: "yo", label: "Yorùbá", englishLabel: "Yoruba", shortLabel: "YO" },
  { code: "ig", label: "Igbo", englishLabel: "Igbo", shortLabel: "IG" },
  { code: "ha", label: "Hausa", englishLabel: "Hausa", shortLabel: "HA" },
  { code: "zu", label: "isiZulu", englishLabel: "Zulu", shortLabel: "ZU" },
  { code: "xh", label: "isiXhosa", englishLabel: "Xhosa", shortLabel: "XH" },
  {
    code: "af",
    label: "Afrikaans",
    englishLabel: "Afrikaans",
    shortLabel: "AF",
  },
  { code: "so", label: "Soomaali", englishLabel: "Somali", shortLabel: "SO" },
  {
    code: "rw",
    label: "Kinyarwanda",
    englishLabel: "Kinyarwanda",
    shortLabel: "RW",
  },
  { code: "ku", label: "Kurdî", englishLabel: "Kurdish", shortLabel: "KU" },

  // ── Americas / Other
  {
    code: "pt-BR",
    label: "Português (Brasil)",
    englishLabel: "Portuguese (Brazil)",
    shortLabel: "PTB",
  },
  { code: "qu", label: "Runasimi", englishLabel: "Quechua", shortLabel: "QU" },
  {
    code: "ht",
    label: "Kreyòl ayisyen",
    englishLabel: "Haitian Creole",
    shortLabel: "HT",
  },

  // ── BLOCKED (Pakistan) — these will not appear in the list
  {
    code: "ur",
    label: "اردو",
    englishLabel: "Urdu",
    shortLabel: "UR",
    blocked: true,
  },
  {
    code: "ps",
    label: "پښتو",
    englishLabel: "Pashto",
    shortLabel: "PS",
    blocked: true,
  },
];

// Active (non-blocked) languages
export const ACTIVE_LANGUAGES = LANGUAGE_OPTIONS.filter((l) => !l.blocked);

// ─────────────────────────────────────────────
// Translation table for core UI strings
// Falls back to English for untranslated keys
// ─────────────────────────────────────────────
const BASE_KEYS = [
  "HOME",
  "SHOP ALL",
  "TRENDING",
  "ABOUT",
  "DASHBOARD",
  "ADMIN",
  "LOGIN",
  "LOGOUT",
  "MEMBER DASHBOARD",
  "AI PRODUCT HUNTER",
  "MY EARNINGS",
  "ANALYTICS & BUYER INTENT",
  "GENERATE SMART LINK",
  "WHATSAPP MARKETING POSTER",
  "Back to Home",
  "Welcome Back",
  "Total Activity",
  "Member Since",
  "Account Status",
  "Active",
  "One World One Future",
] as const;

type TranslationMap = Partial<
  Record<(typeof BASE_KEYS)[number] | string, string>
>;

const translations: Record<string, TranslationMap> = {
  en: {
    HOME: "HOME",
    "SHOP ALL": "SHOP ALL",
    TRENDING: "TRENDING",
    ABOUT: "ABOUT",
    DASHBOARD: "DASHBOARD",
    ADMIN: "ADMIN",
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    "MEMBER DASHBOARD": "MEMBER DASHBOARD",
    "AI PRODUCT HUNTER": "AI PRODUCT HUNTER",
    "MY EARNINGS": "MY EARNINGS",
    "ANALYTICS & BUYER INTENT": "ANALYTICS & BUYER INTENT",
    "GENERATE SMART LINK": "GENERATE SMART LINK",
    "WHATSAPP MARKETING POSTER": "WHATSAPP MARKETING POSTER",
    "Back to Home": "Back to Home",
    "Welcome Back": "Welcome Back",
    "Total Activity": "Total Activity",
    "Member Since": "Member Since",
    "Account Status": "Account Status",
    Active: "Active",
    "One World One Future": "One World One Future",
  },
  hi: {
    HOME: "होम",
    "SHOP ALL": "सभी खरीदें",
    TRENDING: "ट्रेंडिंग",
    ABOUT: "हमारे बारे में",
    DASHBOARD: "डैशबोर्ड",
    ADMIN: "एडमिन",
    LOGIN: "लॉगिन",
    LOGOUT: "लॉगआउट",
    "MEMBER DASHBOARD": "सदस्य डैशबोर्ड",
    "AI PRODUCT HUNTER": "AI प्रोडक्ट हंटर",
    "MY EARNINGS": "मेरी कमाई",
    "ANALYTICS & BUYER INTENT": "एनालिटिक्स और खरीदार इरादा",
    "GENERATE SMART LINK": "स्मार्ट लिंक बनाएं",
    "WHATSAPP MARKETING POSTER": "व्हाट्सएप मार्केटिंग पोस्टर",
    "Back to Home": "होम पर वापस",
    "Welcome Back": "वापस स्वागत है",
    "Total Activity": "कुल गतिविधि",
    "Member Since": "सदस्य कब से",
    "Account Status": "खाता स्थिति",
    Active: "सक्रिय",
    "One World One Future": "एक विश्व एक भविष्य",
  },
  gu: {
    HOME: "હોમ",
    "SHOP ALL": "બધું ખરીદો",
    TRENDING: "ટ્રેન્ડિંગ",
    ABOUT: "અમારા વિશે",
    DASHBOARD: "ડેશબોર્ડ",
    ADMIN: "એડમિન",
    LOGIN: "લૉગઇન",
    LOGOUT: "લૉગઆઉટ",
    "MEMBER DASHBOARD": "સભ્ય ડેશબોર્ડ",
    "AI PRODUCT HUNTER": "AI પ્રોડક્ટ હન્ટર",
    "MY EARNINGS": "મારી કમાણી",
    "ANALYTICS & BUYER INTENT": "એનાલિટિક્સ અને ખરીદદાર ઇરાદો",
    "GENERATE SMART LINK": "સ્માર્ટ લિંક બનાવો",
    "WHATSAPP MARKETING POSTER": "વૉટ્સએપ માર્કેટિંગ પોસ્ટર",
    "Back to Home": "હોમ પર પાછા",
    "Welcome Back": "પાછા સ્વાગત છે",
    "Total Activity": "કુલ પ્રવૃત્તિ",
    "Member Since": "સભ્ય ક્યારથી",
    "Account Status": "ખાતાની સ્થિતિ",
    Active: "સક્રિય",
    "One World One Future": "એક વિશ્વ એક ભવિષ્ય",
  },
  ta: {
    HOME: "முகப்பு",
    "SHOP ALL": "அனைத்தும் வாங்கு",
    TRENDING: "பிரபலமானது",
    ABOUT: "எங்களைப் பற்றி",
    DASHBOARD: "டாஷ்போர்டு",
    ADMIN: "நிர்வாகி",
    LOGIN: "உள்நுழை",
    LOGOUT: "வெளியேறு",
    "MEMBER DASHBOARD": "உறுப்பினர் டாஷ்போர்டு",
    "AI PRODUCT HUNTER": "AI தயாரிப்பு தேடி",
    "MY EARNINGS": "என் வருவாய்",
    "ANALYTICS & BUYER INTENT": "பகுப்பாய்வு & வாங்குபவர் நோக்கம்",
    "GENERATE SMART LINK": "ஸ்மார்ட் இணைப்பை உருவாக்கு",
    "WHATSAPP MARKETING POSTER": "வாட்ஸ்அப் மார்க்கெட்டிங் போஸ்டர்",
    "Back to Home": "முகப்புக்கு திரும்பு",
    "Welcome Back": "மீண்டும் வரவேற்கிறோம்",
    "Total Activity": "மொத்த செயல்பாடு",
    "Member Since": "உறுப்பினர் ஆனது",
    "Account Status": "கணக்கு நிலை",
    Active: "செயலில்",
    "One World One Future": "ஒரு உலகம் ஒரு எதிர்காலம்",
  },
  te: {
    HOME: "హోమ్",
    "SHOP ALL": "అన్నీ కొనండి",
    TRENDING: "ట్రెండింగ్",
    ABOUT: "మా గురించి",
    DASHBOARD: "డాష్‌బోర్డ్",
    ADMIN: "అడ్మిన్",
    LOGIN: "లాగిన్",
    LOGOUT: "లాగౌట్",
    "MEMBER DASHBOARD": "సభ్య డాష్‌బోర్డ్",
    "AI PRODUCT HUNTER": "AI ప్రొడక్ట్ హంటర్",
    "MY EARNINGS": "నా సంపాదన",
    "ANALYTICS & BUYER INTENT": "విశ్లేషణలు & కొనుగోలుదారు ఉద్దేశ్యం",
    "GENERATE SMART LINK": "స్మార్ట్ లింక్ రూపొందించు",
    "WHATSAPP MARKETING POSTER": "వాట్సాప్ మార్కెటింగ్ పోస్టర్",
    "Back to Home": "హోమ్‌కు తిరిగి వెళ్ళు",
    "Welcome Back": "తిరిగి స్వాగతం",
    "Total Activity": "మొత్తం కార్యాచరణ",
    "Member Since": "సభ్యుడైనప్పటి నుండి",
    "Account Status": "ఖాతా స్థితి",
    Active: "యాక్టివ్",
    "One World One Future": "ఒక ప్రపంచం ఒక భవిష్యత్",
  },
  mr: {
    HOME: "होम",
    "SHOP ALL": "सर्व खरेदी करा",
    TRENDING: "ट्रेंडिंग",
    ABOUT: "आमच्याबद्दल",
    DASHBOARD: "डॅशबोर्ड",
    ADMIN: "प्रशासक",
    LOGIN: "लॉगिन",
    LOGOUT: "लॉगआउट",
    "MEMBER DASHBOARD": "सदस्य डॅशबोर्ड",
    "AI PRODUCT HUNTER": "AI उत्पाद शोधक",
    "MY EARNINGS": "माझी कमाई",
    "ANALYTICS & BUYER INTENT": "विश्लेषण आणि खरेदीदार हेतू",
    "GENERATE SMART LINK": "स्मार्ट लिंक तयार करा",
    "WHATSAPP MARKETING POSTER": "व्हाट्सअप मार्केटिंग पोस्टर",
    "Back to Home": "होमवर परत",
    "Welcome Back": "पुन्हा स्वागत आहे",
    "Total Activity": "एकूण क्रियाकलाप",
    "Member Since": "सदस्य कधीपासून",
    "Account Status": "खाते स्थिती",
    Active: "सक्रिय",
    "One World One Future": "एक जग एक भविष्य",
  },
  bn: {
    HOME: "হোম",
    "SHOP ALL": "সব কিনুন",
    TRENDING: "ট্রেন্ডিং",
    ABOUT: "আমাদের সম্পর্কে",
    DASHBOARD: "ড্যাশবোর্ড",
    ADMIN: "অ্যাডমিন",
    LOGIN: "লগইন",
    LOGOUT: "লগআউট",
    "MEMBER DASHBOARD": "সদস্য ড্যাশবোর্ড",
    "AI PRODUCT HUNTER": "AI পণ্য শিকারী",
    "MY EARNINGS": "আমার আয়",
    "ANALYTICS & BUYER INTENT": "বিশ্লেষণ ও ক্রেতার উদ্দেশ্য",
    "GENERATE SMART LINK": "স্মার্ট লিঙ্ক তৈরি করুন",
    "WHATSAPP MARKETING POSTER": "হোয়াটসঅ্যাপ মার্কেটিং পোস্টার",
    "Back to Home": "হোমে ফিরুন",
    "Welcome Back": "আবার স্বাগতম",
    "Total Activity": "মোট কার্যক্রম",
    "Member Since": "সদস্য যখন থেকে",
    "Account Status": "অ্যাকাউন্ট অবস্থা",
    Active: "সক্রিয়",
    "One World One Future": "এক বিশ্ব এক ভবিষ্যৎ",
  },
  kn: {
    HOME: "ಹೋಮ್",
    "SHOP ALL": "ಎಲ್ಲವನ್ನೂ ಕೊಳ್ಳಿ",
    TRENDING: "ಟ್ರೆಂಡಿಂಗ್",
    ABOUT: "ನಮ್ಮ ಬಗ್ಗೆ",
    DASHBOARD: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    ADMIN: "ಅಡ್ಮಿನ್",
    LOGIN: "ಲಾಗಿನ್",
    LOGOUT: "ಲಾಗ್ ಔಟ್",
    "MEMBER DASHBOARD": "ಸದಸ್ಯ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "AI PRODUCT HUNTER": "AI ಉತ್ಪನ್ನ ಶಿಕಾರಿ",
    "MY EARNINGS": "ನನ್ನ ಗಳಿಕೆ",
    "ANALYTICS & BUYER INTENT": "ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ಖರೀದಿದಾರ ಉದ್ದೇಶ",
    "GENERATE SMART LINK": "ಸ್ಮಾರ್ಟ್ ಲಿಂಕ್ ರಚಿಸಿ",
    "WHATSAPP MARKETING POSTER": "ವಾಟ್ಸಾಪ್ ಮಾರ್ಕೆಟಿಂಗ್ ಪೋಸ್ಟರ್",
    "Back to Home": "ಹೋಮ್‌ಗೆ ಹಿಂತಿರುಗಿ",
    "Welcome Back": "ಮತ್ತೆ ಸ್ವಾಗತ",
    "Total Activity": "ಒಟ್ಟು ಚಟುವಟಿಕೆ",
    "Member Since": "ಸದಸ್ಯ ಯಾವಾಗಿನಿಂದ",
    "Account Status": "ಖಾತೆ ಸ್ಥಿತಿ",
    Active: "ಸಕ್ರಿಯ",
    "One World One Future": "ಒಂದು ಜಗತ್ತು ಒಂದು ಭವಿಷ್ಯ",
  },
  ml: {
    HOME: "ഹോം",
    "SHOP ALL": "എല്ലാം വാങ്ങൂ",
    TRENDING: "ട്രെൻഡിങ്",
    ABOUT: "ഞങ്ങളെ കുറിച്ച്",
    DASHBOARD: "ഡാഷ്‌ബോർഡ്",
    ADMIN: "അഡ്മിൻ",
    LOGIN: "ലോഗിൻ",
    LOGOUT: "ലോഗൗട്ട്",
    "MEMBER DASHBOARD": "അംഗ ഡാഷ്‌ബോർഡ്",
    "AI PRODUCT HUNTER": "AI ഉൽപ്പന്ന ഹണ്ടർ",
    "MY EARNINGS": "എന്റെ വരുമാനം",
    "ANALYTICS & BUYER INTENT": "വിശകലനം & വാങ്ങുന്നവരുടെ ഉദ്ദേശ്യം",
    "GENERATE SMART LINK": "സ്മാർട്ട് ലിങ്ക് ഉണ്ടാക്കൂ",
    "WHATSAPP MARKETING POSTER": "വാട്ട്‌സ്ആപ്പ് മാർക്കറ്റിംഗ് പോസ്റ്റർ",
    "Back to Home": "ഹോമിലേക്ക് മടങ്ങൂ",
    "Welcome Back": "തിരിച്ചു സ്വാഗതം",
    "Total Activity": "ആകെ പ്രവർത്തനം",
    "Member Since": "അംഗമായ കാലം",
    "Account Status": "അക്കൗണ്ട് സ്ഥിതി",
    Active: "സജീവം",
    "One World One Future": "ഒരു ലോകം ഒരു ഭാവി",
  },
  pa: {
    HOME: "ਹੋਮ",
    "SHOP ALL": "ਸਭ ਖਰੀਦੋ",
    TRENDING: "ਟ੍ਰੈਂਡਿੰਗ",
    ABOUT: "ਸਾਡੇ ਬਾਰੇ",
    DASHBOARD: "ਡੈਸ਼ਬੋਰਡ",
    ADMIN: "ਐਡਮਿਨ",
    LOGIN: "ਲੌਗਇਨ",
    LOGOUT: "ਲੌਗਆਊਟ",
    "MEMBER DASHBOARD": "ਮੈਂਬਰ ਡੈਸ਼ਬੋਰਡ",
    "AI PRODUCT HUNTER": "AI ਉਤਪਾਦ ਸ਼ਿਕਾਰੀ",
    "MY EARNINGS": "ਮੇਰੀ ਕਮਾਈ",
    "ANALYTICS & BUYER INTENT": "ਵਿਸ਼ਲੇਸ਼ਣ ਅਤੇ ਖਰੀਦਦਾਰ ਇਰਾਦਾ",
    "GENERATE SMART LINK": "ਸਮਾਰਟ ਲਿੰਕ ਬਣਾਓ",
    "WHATSAPP MARKETING POSTER": "ਵਟਸਐਪ ਮਾਰਕੀਟਿੰਗ ਪੋਸਟਰ",
    "Back to Home": "ਹੋਮ ਤੇ ਵਾਪਸ",
    "Welcome Back": "ਵਾਪਸ ਜੀ ਆਇਆਂ",
    "Total Activity": "ਕੁੱਲ ਗਤੀਵਿਧੀ",
    "Member Since": "ਮੈਂਬਰ ਕਦੋਂ ਤੋਂ",
    "Account Status": "ਖਾਤੇ ਦੀ ਸਥਿਤੀ",
    Active: "ਸਰਗਰਮ",
    "One World One Future": "ਇੱਕ ਸੰਸਾਰ ਇੱਕ ਭਵਿੱਖ",
  },
  es: {
    HOME: "INICIO",
    "SHOP ALL": "VER TODO",
    TRENDING: "TENDENCIAS",
    ABOUT: "ACERCA DE",
    DASHBOARD: "PANEL",
    ADMIN: "ADMIN",
    LOGIN: "ENTRAR",
    LOGOUT: "SALIR",
    "MEMBER DASHBOARD": "PANEL DE MIEMBRO",
    "AI PRODUCT HUNTER": "BUSCADOR AI DE PRODUCTOS",
    "MY EARNINGS": "MIS GANANCIAS",
    "ANALYTICS & BUYER INTENT": "ANALÍTICAS E INTENCIÓN DE COMPRA",
    "GENERATE SMART LINK": "GENERAR ENLACE INTELIGENTE",
    "WHATSAPP MARKETING POSTER": "PÓSTER DE MARKETING WHATSAPP",
    "Back to Home": "Volver al Inicio",
    "Welcome Back": "Bienvenido de Nuevo",
    "Total Activity": "Actividad Total",
    "Member Since": "Miembro Desde",
    "Account Status": "Estado de Cuenta",
    Active: "Activo",
    "One World One Future": "Un Mundo Un Futuro",
  },
  fr: {
    HOME: "ACCUEIL",
    "SHOP ALL": "TOUT ACHETER",
    TRENDING: "TENDANCES",
    ABOUT: "À PROPOS",
    DASHBOARD: "TABLEAU DE BORD",
    ADMIN: "ADMIN",
    LOGIN: "CONNEXION",
    LOGOUT: "DÉCONNEXION",
    "MEMBER DASHBOARD": "TABLEAU DE BORD MEMBRE",
    "AI PRODUCT HUNTER": "CHASSEUR DE PRODUITS AI",
    "MY EARNINGS": "MES GAINS",
    "ANALYTICS & BUYER INTENT": "ANALYSES ET INTENTION D'ACHAT",
    "GENERATE SMART LINK": "GÉNÉRER UN LIEN INTELLIGENT",
    "WHATSAPP MARKETING POSTER": "AFFICHE MARKETING WHATSAPP",
    "Back to Home": "Retour à l'accueil",
    "Welcome Back": "Bon retour",
    "Total Activity": "Activité Totale",
    "Member Since": "Membre Depuis",
    "Account Status": "Statut du Compte",
    Active: "Actif",
    "One World One Future": "Un Monde Un Avenir",
  },
  de: {
    HOME: "START",
    "SHOP ALL": "ALLE KAUFEN",
    TRENDING: "TRENDS",
    ABOUT: "ÜBER UNS",
    DASHBOARD: "DASHBOARD",
    ADMIN: "ADMIN",
    LOGIN: "ANMELDEN",
    LOGOUT: "ABMELDEN",
    "MEMBER DASHBOARD": "MITGLIEDER-DASHBOARD",
    "AI PRODUCT HUNTER": "KI-PRODUKTSUCHE",
    "MY EARNINGS": "MEINE EINNAHMEN",
    "ANALYTICS & BUYER INTENT": "ANALYSEN & KÄUFERABSICHT",
    "GENERATE SMART LINK": "SMART-LINK ERSTELLEN",
    "WHATSAPP MARKETING POSTER": "WHATSAPP MARKETING POSTER",
    "Back to Home": "Zurück zur Startseite",
    "Welcome Back": "Willkommen zurück",
    "Total Activity": "Gesamtaktivität",
    "Member Since": "Mitglied seit",
    "Account Status": "Kontostatus",
    Active: "Aktiv",
    "One World One Future": "Eine Welt Eine Zukunft",
  },
  ar: {
    HOME: "الرئيسية",
    "SHOP ALL": "تسوق الكل",
    TRENDING: "الرائج",
    ABOUT: "عن الموقع",
    DASHBOARD: "لوحة التحكم",
    ADMIN: "المشرف",
    LOGIN: "دخول",
    LOGOUT: "خروج",
    "MEMBER DASHBOARD": "لوحة تحكم العضو",
    "AI PRODUCT HUNTER": "صائد المنتجات بالذكاء الاصطناعي",
    "MY EARNINGS": "أرباحي",
    "ANALYTICS & BUYER INTENT": "التحليلات ونية المشتري",
    "GENERATE SMART LINK": "إنشاء رابط ذكي",
    "WHATSAPP MARKETING POSTER": "ملصق تسويق واتساب",
    "Back to Home": "العودة للرئيسية",
    "Welcome Back": "أهلاً بعودتك",
    "Total Activity": "إجمالي النشاط",
    "Member Since": "عضو منذ",
    "Account Status": "حالة الحساب",
    Active: "نشط",
    "One World One Future": "عالم واحد مستقبل واحد",
  },
  ja: {
    HOME: "ホーム",
    "SHOP ALL": "全て購入",
    TRENDING: "トレンド",
    ABOUT: "会社概要",
    DASHBOARD: "ダッシュボード",
    ADMIN: "管理者",
    LOGIN: "ログイン",
    LOGOUT: "ログアウト",
    "MEMBER DASHBOARD": "会員ダッシュボード",
    "AI PRODUCT HUNTER": "AI製品ハンター",
    "MY EARNINGS": "私の収益",
    "ANALYTICS & BUYER INTENT": "分析と購買意図",
    "GENERATE SMART LINK": "スマートリンクを生成",
    "WHATSAPP MARKETING POSTER": "WhatsAppマーケティングポスター",
    "Back to Home": "ホームに戻る",
    "Welcome Back": "おかえりなさい",
    "Total Activity": "総アクティビティ",
    "Member Since": "会員開始日",
    "Account Status": "アカウント状態",
    Active: "アクティブ",
    "One World One Future": "一つの世界 一つの未来",
  },
  zh: {
    HOME: "主页",
    "SHOP ALL": "全部购买",
    TRENDING: "热门",
    ABOUT: "关于我们",
    DASHBOARD: "仪表板",
    ADMIN: "管理员",
    LOGIN: "登录",
    LOGOUT: "退出",
    "MEMBER DASHBOARD": "会员仪表板",
    "AI PRODUCT HUNTER": "AI产品猎手",
    "MY EARNINGS": "我的收益",
    "ANALYTICS & BUYER INTENT": "分析与购买意图",
    "GENERATE SMART LINK": "生成智能链接",
    "WHATSAPP MARKETING POSTER": "WhatsApp营销海报",
    "Back to Home": "返回主页",
    "Welcome Back": "欢迎回来",
    "Total Activity": "总活动",
    "Member Since": "会员自",
    "Account Status": "账户状态",
    Active: "活跃",
    "One World One Future": "同一个世界 同一个未来",
  },
  ko: {
    HOME: "홈",
    "SHOP ALL": "전체 구매",
    TRENDING: "트렌딩",
    ABOUT: "회사 소개",
    DASHBOARD: "대시보드",
    ADMIN: "관리자",
    LOGIN: "로그인",
    LOGOUT: "로그아웃",
    "MEMBER DASHBOARD": "회원 대시보드",
    "AI PRODUCT HUNTER": "AI 제품 헌터",
    "MY EARNINGS": "내 수익",
    "ANALYTICS & BUYER INTENT": "분석 및 구매자 의도",
    "GENERATE SMART LINK": "스마트 링크 생성",
    "WHATSAPP MARKETING POSTER": "WhatsApp 마케팅 포스터",
    "Back to Home": "홈으로 돌아가기",
    "Welcome Back": "돌아오신 것을 환영합니다",
    "Total Activity": "총 활동",
    "Member Since": "회원 가입일",
    "Account Status": "계정 상태",
    Active: "활성",
    "One World One Future": "하나의 세계 하나의 미래",
  },
  pt: {
    HOME: "INÍCIO",
    "SHOP ALL": "COMPRAR TUDO",
    TRENDING: "TENDÊNCIAS",
    ABOUT: "SOBRE NÓS",
    DASHBOARD: "PAINEL",
    ADMIN: "ADMIN",
    LOGIN: "ENTRAR",
    LOGOUT: "SAIR",
    "MEMBER DASHBOARD": "PAINEL DO MEMBRO",
    "AI PRODUCT HUNTER": "CAÇADOR DE PRODUTOS AI",
    "MY EARNINGS": "MEUS GANHOS",
    "ANALYTICS & BUYER INTENT": "ANÁLISES E INTENÇÃO DO COMPRADOR",
    "GENERATE SMART LINK": "GERAR LINK INTELIGENTE",
    "WHATSAPP MARKETING POSTER": "POSTER DE MARKETING WHATSAPP",
    "Back to Home": "Voltar ao Início",
    "Welcome Back": "Bem-vindo de Volta",
    "Total Activity": "Atividade Total",
    "Member Since": "Membro Desde",
    "Account Status": "Status da Conta",
    Active: "Ativo",
    "One World One Future": "Um Mundo Um Futuro",
  },
  ru: {
    HOME: "ГЛАВНАЯ",
    "SHOP ALL": "КУПИТЬ ВСЕ",
    TRENDING: "ТРЕНДЫ",
    ABOUT: "О НАС",
    DASHBOARD: "ПАНЕЛЬ",
    ADMIN: "АДМИН",
    LOGIN: "ВХОД",
    LOGOUT: "ВЫХОД",
    "MEMBER DASHBOARD": "ПАНЕЛЬ УЧАСТНИКА",
    "AI PRODUCT HUNTER": "ИИ-ОХОТНИК ЗА ПРОДУКТАМИ",
    "MY EARNINGS": "МОИ ДОХОДЫ",
    "ANALYTICS & BUYER INTENT": "АНАЛИТИКА И НАМЕРЕНИЯ ПОКУПАТЕЛЯ",
    "GENERATE SMART LINK": "СОЗДАТЬ УМНУЮ ССЫЛКУ",
    "WHATSAPP MARKETING POSTER": "МАРКЕТИНГОВЫЙ ПОСТЕР WHATSAPP",
    "Back to Home": "Вернуться на главную",
    "Welcome Back": "С возвращением",
    "Total Activity": "Всего активности",
    "Member Since": "Участник с",
    "Account Status": "Статус аккаунта",
    Active: "Активен",
    "One World One Future": "Один Мир Одно Будущее",
  },
  it: {
    HOME: "HOME",
    "SHOP ALL": "ACQUISTA TUTTO",
    TRENDING: "TENDENZE",
    ABOUT: "CHI SIAMO",
    DASHBOARD: "DASHBOARD",
    ADMIN: "ADMIN",
    LOGIN: "ACCEDI",
    LOGOUT: "ESCI",
    "MEMBER DASHBOARD": "PANNELLO MEMBRO",
    "AI PRODUCT HUNTER": "CACCIATORE DI PRODOTTI AI",
    "MY EARNINGS": "I MIEI GUADAGNI",
    "ANALYTICS & BUYER INTENT": "ANALISI E INTENZIONE D'ACQUISTO",
    "GENERATE SMART LINK": "GENERA LINK INTELLIGENTE",
    "WHATSAPP MARKETING POSTER": "POSTER MARKETING WHATSAPP",
    "Back to Home": "Torna alla Home",
    "Welcome Back": "Bentornato",
    "Total Activity": "Attività Totale",
    "Member Since": "Membro dal",
    "Account Status": "Stato Account",
    Active: "Attivo",
    "One World One Future": "Un Mondo Un Futuro",
  },
  tr: {
    HOME: "ANA SAYFA",
    "SHOP ALL": "HEPSİNİ AL",
    TRENDING: "TREND",
    ABOUT: "HAKKIMIZDA",
    DASHBOARD: "GÖSTERGE PANELİ",
    ADMIN: "YÖNETİCİ",
    LOGIN: "GİRİŞ",
    LOGOUT: "ÇIKIŞ",
    "MEMBER DASHBOARD": "ÜYE PANELI",
    "AI PRODUCT HUNTER": "AI ÜRÜN AVCISI",
    "MY EARNINGS": "KAZANÇLARIM",
    "ANALYTICS & BUYER INTENT": "ANALİTİK VE ALICI NİYETİ",
    "GENERATE SMART LINK": "AKILLI BAĞLANTI OLUŞTUR",
    "WHATSAPP MARKETING POSTER": "WHATSAPP PAZARLAMA POSTERI",
    "Back to Home": "Ana Sayfaya Dön",
    "Welcome Back": "Tekrar Hoş Geldiniz",
    "Total Activity": "Toplam Aktivite",
    "Member Since": "Üyelik Tarihi",
    "Account Status": "Hesap Durumu",
    Active: "Aktif",
    "One World One Future": "Bir Dünya Bir Gelecek",
  },
  id: {
    HOME: "BERANDA",
    "SHOP ALL": "BELI SEMUA",
    TRENDING: "TRENDING",
    ABOUT: "TENTANG KAMI",
    DASHBOARD: "DASBOR",
    ADMIN: "ADMIN",
    LOGIN: "MASUK",
    LOGOUT: "KELUAR",
    "MEMBER DASHBOARD": "DASBOR ANGGOTA",
    "AI PRODUCT HUNTER": "PEMBURU PRODUK AI",
    "MY EARNINGS": "PENGHASILAN SAYA",
    "ANALYTICS & BUYER INTENT": "ANALITIK & NIAT PEMBELI",
    "GENERATE SMART LINK": "BUAT TAUTAN CERDAS",
    "WHATSAPP MARKETING POSTER": "POSTER PEMASARAN WHATSAPP",
    "Back to Home": "Kembali ke Beranda",
    "Welcome Back": "Selamat Datang Kembali",
    "Total Activity": "Total Aktivitas",
    "Member Since": "Anggota Sejak",
    "Account Status": "Status Akun",
    Active: "Aktif",
    "One World One Future": "Satu Dunia Satu Masa Depan",
  },
  sw: {
    HOME: "NYUMBANI",
    "SHOP ALL": "NUNUA YOTE",
    TRENDING: "MAARUFU",
    ABOUT: "KUHUSU SISI",
    DASHBOARD: "DASHIBODI",
    ADMIN: "MSIMAMIZI",
    LOGIN: "INGIA",
    LOGOUT: "TOKA",
    "MEMBER DASHBOARD": "DASHIBODI YA MWANACHAMA",
    "AI PRODUCT HUNTER": "MWINDAJI WA BIDHAA AI",
    "MY EARNINGS": "MAPATO YANGU",
    "ANALYTICS & BUYER INTENT": "UCHANGANUZI NA NIA YA MNUNUZI",
    "GENERATE SMART LINK": "TENGENEZA KIUNGO CHENYE AKILI",
    "WHATSAPP MARKETING POSTER": "BANGO LA MASOKO YA WHATSAPP",
    "Back to Home": "Rudi Nyumbani",
    "Welcome Back": "Karibu Tena",
    "Total Activity": "Jumla ya Shughuli",
    "Member Since": "Mwanachama Tangu",
    "Account Status": "Hali ya Akaunti",
    Active: "Amilifu",
    "One World One Future": "Ulimwengu Mmoja Mustakabali Mmoja",
  },
};

interface LanguageContextValue {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
  currentOption: LanguageOption;
}

const LanguageContext = createContext<LanguageContextValue>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
  currentOption: ACTIVE_LANGUAGES[0],
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<string>("en");

  const t = (key: string): string => {
    const map = translations[language];
    if (map && key in map) return map[key] as string;
    // fallback to English
    const en = translations.en;
    if (en && key in en) return en[key] as string;
    return key;
  };

  const currentOption =
    ACTIVE_LANGUAGES.find((l) => l.code === language) ?? ACTIVE_LANGUAGES[0];

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, t, currentOption }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

// Keep the old Language type alias for backward compatibility
export type Language = string;
