/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'shoesAndClothes' : IDL.Null,
  'tech' : IDL.Null,
  'toys' : IDL.Null,
  'technology' : IDL.Null,
  'wellness' : IDL.Null,
  'books' : IDL.Null,
  'lifestyle' : IDL.Null,
});
export const Product = IDL.Record({
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'description' : IDL.Text,
  'qualityScore' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'aiReview' : IDL.Text,
});
export const ProductId = IDL.Nat;
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'joinDate' : Time,
  'name' : IDL.Text,
  'activityCount' : IDL.Nat,
});
export const SiteSettings = IDL.Record({
  'siteTitle' : IDL.Text,
  'announcementText' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProduct' : IDL.Func([Product], [ProductId], []),
  'deleteAllProducts' : IDL.Func([], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllProducts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(ProductId, Product))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLiveVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getMemberStats' : IDL.Func(
      [],
      [IDL.Opt(IDL.Record({ 'joinDate' : Time, 'activityCount' : IDL.Nat }))],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(IDL.Tuple(ProductId, Product))],
      ['query'],
    ),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'trackVisitor' : IDL.Func([], [], []),
  'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
  'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'shoesAndClothes' : IDL.Null,
    'tech' : IDL.Null,
    'toys' : IDL.Null,
    'technology' : IDL.Null,
    'wellness' : IDL.Null,
    'books' : IDL.Null,
    'lifestyle' : IDL.Null,
  });
  const Product = IDL.Record({
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'description' : IDL.Text,
    'qualityScore' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'aiReview' : IDL.Text,
  });
  const ProductId = IDL.Nat;
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'joinDate' : Time,
    'name' : IDL.Text,
    'activityCount' : IDL.Nat,
  });
  const SiteSettings = IDL.Record({
    'siteTitle' : IDL.Text,
    'announcementText' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProduct' : IDL.Func([Product], [ProductId], []),
    'deleteAllProducts' : IDL.Func([], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllProducts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ProductId, Product))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLiveVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getMemberStats' : IDL.Func(
        [],
        [IDL.Opt(IDL.Record({ 'joinDate' : Time, 'activityCount' : IDL.Nat }))],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(IDL.Tuple(ProductId, Product))],
        ['query'],
      ),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'trackVisitor' : IDL.Func([], [], []),
    'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
    'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };