/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'shoesAndClothes' : null } |
  { 'tech' : null } |
  { 'toys' : null } |
  { 'technology' : null } |
  { 'wellness' : null } |
  { 'books' : null } |
  { 'lifestyle' : null };
export interface Product {
  'title' : string,
  'featured' : boolean,
  'description' : string,
  'qualityScore' : bigint,
  'imageUrl' : string,
  'category' : Category,
  'aiReview' : string,
}
export type ProductId = bigint;
export interface SiteSettings {
  'siteTitle' : string,
  'announcementText' : string,
}
export type Time = bigint;
export interface UserProfile {
  'joinDate' : Time,
  'name' : string,
  'activityCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProduct' : ActorMethod<[Product], ProductId>,
  'deleteAllProducts' : ActorMethod<[], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllProducts' : ActorMethod<[], Array<[ProductId, Product]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLiveVisitorCount' : ActorMethod<[], bigint>,
  'getMemberStats' : ActorMethod<
    [],
    [] | [{ 'joinDate' : Time, 'activityCount' : bigint }]
  >,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<
    [Category],
    Array<[ProductId, Product]>
  >,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitorCount' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'trackVisitor' : ActorMethod<[], undefined>,
  'updateProduct' : ActorMethod<[bigint, Product], undefined>,
  'updateSiteSettings' : ActorMethod<[SiteSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];