/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VendorRequest {
    id: bigint;
    websiteLink: string;
    status: string;
    businessName: string;
    submittedAt: Time;
    description: string;
    productName: string;
    contactEmail: string;
    category: string;
    price: number;
    vendorName: string;
}
export type Time = bigint;
export interface SiteSettings {
    siteTitle: string;
    announcementText: string;
}
export interface InventoryProduct {
    id: bigint;
    name: string;
    category: string;
    affiliateLink: string;
    price: number;
}
export type ProductId = bigint;
export interface Order {
    id: bigint;
    productName: string;
    assignedMemberId: string;
    timestamp: Time;
    memberIndex: bigint;
}
export interface UserProfile {
    joinDate: Time;
    name: string;
    activityCount: bigint;
}
export interface Product {
    title: string;
    featured: boolean;
    description: string;
    qualityScore: bigint;
    imageUrl: string;
    category: Category;
    aiReview: string;
}
export enum Category {
    shoesAndClothes = "shoesAndClothes",
    tech = "tech",
    toys = "toys",
    technology = "technology",
    wellness = "wellness",
    books = "books",
    lifestyle = "lifestyle"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAutoPostCategory(category: string): Promise<void>;
    addInventoryProduct(name: string, price: number, category: string, affiliateLink: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createProduct(originalProduct: Product): Promise<ProductId>;
    deleteAllProducts(): Promise<void>;
    deleteInventoryProduct(id: bigint): Promise<void>;
    deleteProduct(productId: bigint): Promise<void>;
    getAllInventoryProducts(): Promise<Array<[bigint, InventoryProduct]>>;
    getAllProducts(): Promise<Array<[ProductId, Product]>>;
    getAutoPostCategories(): Promise<Array<string>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLiveVisitorCount(): Promise<bigint>;
    getMemberStats(): Promise<{
        joinDate: Time;
        activityCount: bigint;
    } | null>;
    getOrders(): Promise<Array<[bigint, Order]>>;
    getProduct(productId: bigint): Promise<Product | null>;
    getProductsByCategory(category: Category): Promise<Array<[ProductId, Product]>>;
    getRoundRobinIndex(): Promise<bigint>;
    getSiteSettings(): Promise<SiteSettings>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVendorRequests(): Promise<Array<[bigint, VendorRequest]>>;
    getVisitorCount(): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    isCategoryAutoPosted(category: string): Promise<boolean>;
    listAllUsers(): Promise<Array<[Principal, UserProfile]>>;
    removeAutoPostCategory(category: string): Promise<void>;
    resetRoundRobinIndex(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitOrder(productName: string, totalMembers: bigint): Promise<bigint>;
    submitVendorRequest(newRequest: VendorRequest): Promise<bigint>;
    trackVisitor(): Promise<void>;
    updateInventoryProduct(id: bigint, name: string, price: number, category: string, affiliateLink: string): Promise<void>;
    updateProduct(productId: bigint, product: Product): Promise<void>;
    updateSiteSettings(newSettings: SiteSettings): Promise<void>;
    updateVendorRequestStatus(id: bigint, status: string): Promise<void>;
}
import type { Category as _Category, Product as _Product, ProductId as _ProductId, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAutoPostCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAutoPostCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAutoPostCategory(arg0);
            return result;
        }
    }
    async addInventoryProduct(arg0: string, arg1: number, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addInventoryProduct(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInventoryProduct(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createProduct(arg0: Product): Promise<ProductId> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(to_candid_Product_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(to_candid_Product_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteAllProducts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllProducts();
            return result;
        }
    }
    async deleteInventoryProduct(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInventoryProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInventoryProduct(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getAllInventoryProducts(): Promise<Array<[bigint, InventoryProduct]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInventoryProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInventoryProducts();
            return result;
        }
    }
    async getAllProducts(): Promise<Array<[ProductId, Product]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAutoPostCategories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAutoPostCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAutoPostCategories();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLiveVisitorCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiveVisitorCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiveVisitorCount();
            return result;
        }
    }
    async getMemberStats(): Promise<{
        joinDate: Time;
        activityCount: bigint;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberStats();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberStats();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrders(): Promise<Array<[bigint, Order]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return result;
        }
    }
    async getProduct(arg0: bigint): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: Category): Promise<Array<[ProductId, Product]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(to_candid_Category_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(to_candid_Category_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoundRobinIndex(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoundRobinIndex();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoundRobinIndex();
            return result;
        }
    }
    async getSiteSettings(): Promise<SiteSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteSettings();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVendorRequests(): Promise<Array<[bigint, VendorRequest]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendorRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendorRequests();
            return result;
        }
    }
    async getVisitorCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisitorCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisitorCount();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCategoryAutoPosted(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCategoryAutoPosted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCategoryAutoPosted(arg0);
            return result;
        }
    }
    async listAllUsers(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return result;
        }
    }
    async removeAutoPostCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAutoPostCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAutoPostCategory(arg0);
            return result;
        }
    }
    async resetRoundRobinIndex(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetRoundRobinIndex();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetRoundRobinIndex();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitOrder(arg0: string, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitOrder(arg0, arg1);
            return result;
        }
    }
    async submitVendorRequest(arg0: VendorRequest): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitVendorRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitVendorRequest(arg0);
            return result;
        }
    }
    async trackVisitor(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trackVisitor();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackVisitor();
            return result;
        }
    }
    async updateInventoryProduct(arg0: bigint, arg1: string, arg2: number, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventoryProduct(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventoryProduct(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateProduct(arg0: bigint, arg1: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, to_candid_Product_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, to_candid_Product_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSiteSettings(arg0: SiteSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSiteSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSiteSettings(arg0);
            return result;
        }
    }
    async updateVendorRequestStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVendorRequestStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVendorRequestStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Category_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        joinDate: _Time;
        activityCount: bigint;
    }]): {
    joinDate: Time;
    activityCount: bigint;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    featured: boolean;
    description: string;
    qualityScore: bigint;
    imageUrl: string;
    category: _Category;
    aiReview: string;
}): {
    title: string;
    featured: boolean;
    description: string;
    qualityScore: bigint;
    imageUrl: string;
    category: Category;
    aiReview: string;
} {
    return {
        title: value.title,
        featured: value.featured,
        description: value.description,
        qualityScore: value.qualityScore,
        imageUrl: value.imageUrl,
        category: from_candid_Category_n11(_uploadFile, _downloadFile, value.category),
        aiReview: value.aiReview
    };
}
function from_candid_tuple_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_ProductId, _Product]): [ProductId, Product] {
    return [
        value[0],
        from_candid_Product_n9(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shoesAndClothes: null;
} | {
    tech: null;
} | {
    toys: null;
} | {
    technology: null;
} | {
    wellness: null;
} | {
    books: null;
} | {
    lifestyle: null;
}): Category {
    return "shoesAndClothes" in value ? Category.shoesAndClothes : "tech" in value ? Category.tech : "toys" in value ? Category.toys : "technology" in value ? Category.technology : "wellness" in value ? Category.wellness : "books" in value ? Category.books : "lifestyle" in value ? Category.lifestyle : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_ProductId, _Product]>): Array<[ProductId, Product]> {
    return value.map((x)=>from_candid_tuple_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Product_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): _Product {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    featured: boolean;
    description: string;
    qualityScore: bigint;
    imageUrl: string;
    category: Category;
    aiReview: string;
}): {
    title: string;
    featured: boolean;
    description: string;
    qualityScore: bigint;
    imageUrl: string;
    category: _Category;
    aiReview: string;
} {
    return {
        title: value.title,
        featured: value.featured,
        description: value.description,
        qualityScore: value.qualityScore,
        imageUrl: value.imageUrl,
        category: to_candid_Category_n5(_uploadFile, _downloadFile, value.category),
        aiReview: value.aiReview
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    shoesAndClothes: null;
} | {
    tech: null;
} | {
    toys: null;
} | {
    technology: null;
} | {
    wellness: null;
} | {
    books: null;
} | {
    lifestyle: null;
} {
    return value == Category.shoesAndClothes ? {
        shoesAndClothes: null
    } : value == Category.tech ? {
        tech: null
    } : value == Category.toys ? {
        toys: null
    } : value == Category.technology ? {
        technology: null
    } : value == Category.wellness ? {
        wellness: null
    } : value == Category.books ? {
        books: null
    } : value == Category.lifestyle ? {
        lifestyle: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
